version: 2
jobs:
  build:
    working_directory: ~/purge
    docker:
      - image: circleci/node:8.9.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Install node_modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Testing
          command: npm run test
      - run:
          name: Bulding
          command: npm run build
      - save_cache:
          key: angular-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - public

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
  
  